//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sesion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buildings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buildings()
        {
            this.apartments = new HashSet<apartments>();
            this.fees = new HashSet<fees>();
        }
    
        public int buildingId { get; set; }
        public string buildingdName { get; set; }
        public string buildingDescription { get; set; }
        public Nullable<double> buildingWaterReturnValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apartments> apartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fees> fees { get; set; }
    }
}
