//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sesion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TADSICondominiumEntities : DbContext
    {
        public TADSICondominiumEntities()
            : base("name=TADSICondominiumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartments> apartments { get; set; }
        public virtual DbSet<buildings> buildings { get; set; }
        public virtual DbSet<complains> complains { get; set; }
        public virtual DbSet<fees> fees { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<visits> visits { get; set; }
    }
}
