//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sesion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int paymentId { get; set; }
        public Nullable<int> apartmentId { get; set; }
        public double paymentValue { get; set; }
        public string paymentType { get; set; }
    
        public virtual apartments apartments { get; set; }
    }
}
